version: '2.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "33062:3306"

  wordpress:
    depends_on:
      - db
    image: wordpress
    volumes:
      - ./:/var/www/html/wp-content/plugins
    restart: always
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: secret